package com.re.paas.internal.core.keys;

public class ConfigKeys {

	public static final String CURRENT_PLATFORM_VERSION = "CURRENT_PLATFORM_VERSION";
	public static final String IS_INSTALLED = "IS_INSTALLED";
	
	public static final String $INTERVAL_CRON_LAST_EXECUTION_TIME = "$INTERVAL_CRON_LAST_EXECUTION_TIME";
	
	public static final String ORGANIZATION_NAME = "ORGANIZATION_NAME";
	public static final String ORGANIZATION_LOGO_URL = "ORGANIZATION_LOGO";
	public static final String ORGANIZATION_COUNTRY = "ORGANIZATION_COUNTRY";
	
	public static final String ORGANIZATION_AUDIENCE = "ORGANIZATION_AUDIENCE";
	
	
	public static final String DEFAULT_CURRENCY = "DEFAULT_CURRENCY";
	public static final String DEFAULT_TIMEZONE = "DEFAULT_TIMEZONE";
	public static final String DEFAULT_LOCALE = "DEFAULT_LOCALE";
	
	public static final String MAIL_PROVIDER_URL = "MAIL_PROVIDER_URL";
	public static final String MAIL_PROVIDER_USERNAME = "MAIL_PROVIDER_USERNAME";
	public static final String MAIL_PROVIDER_PASSWORD = "MAIL_PROVIDER_PASSWORD";
	
	public static final String PAYMENT_SETTLEMENT_CRON_JOB_ID = "PAYMENT_SETTLEMENT_CRON_JOB_ID";
	public static final String PAYMENT_SETTLEMENT_CRON_INTERVAL = "PAYMENT_SETTLEMENT_CRON_INTERVAL";
	
	public static final String AYDEN_SETTINGS_FORM_SECTION_ID = "AYDEN_FORM_SECTION_ID";
	
	public static final String AYDEN_USERNAME_FIELD_ID = "AYDEN_USERNAME_FIELD_ID";
	public static final String AYDEN_PASSWORD_FIELD_ID = "AYDEN_PASSWORD_FIELD_ID";
	public static final String AYDEN_APPLICATION_NAME_FIELD_ID = "AYDEN_APPLICATION_NAME_FIELD_ID";
	public static final String AYDEN_LIVE_ENVIRONMENT_FIELD_ID = "AYDEN_LIVE_ENVIRONMENT_FIELD_ID";
	public static final String AYDEN_NOTIFICATION_SERVER_AUTH_USERNAME_FIELD_ID = "AYDEN_NOTIFICATION_SERVER_AUTH_USERNAME_FIELD_ID";
	public static final String AYDEN_NOTIFICATION_SERVER_AUTH_PASSWORD_FIELD_ID = "AYDEN_NOTIFICATION_SERVER_AUTH_PASSWORD_FIELD_ID";
	
	
	public static final String INFOBIP_SETTINGS_FORM_SECTION_ID = "INFOBIP_SETTINGS_FORM_SECTION_ID";
	
	public static final String INFOBIP_BASEURL_FIELD_ID = "INFOBIP_BASEURL_FIELD_ID";
	public static final String INFOBIP_USERNAME_FIELD_ID = "INFOBIP_USERNAME_FIELD_ID";
	public static final String INFOBIP_PASSWORD_FIELD_ID = "INFOBIP_PASSWORD_FIELD_ID";

	
	public static final String $REALM_APPLICATION_FORM_BLOB_ID = "$REALM_APPLICATION_FORM";

	public static final String USER_COUNT_ARCHIVE = "USER_COUNT_ARCHIVE";
	public static final String USER_COUNT_CURRENT = "USER_COUNT_CURRENT";
	
	public static final String ACTIVITY_STREAM_ENABLED = "ACTIVITY_STREAM_ENABLED";
	public static final String DEFAULT_ACTIVITY_STREAM_TIMELINE = "DEFAULT_ACTIVITY_STREAM_TIMELINE";
	
	public static final String ENABLE_CLIENT_SIDE_PROPERTY_LISTING_CTX_CREATION = "ENABLE_CLIENT_SIDE_PROPERTY_LISTING_CTX_CREATION";
	
	public static final String CURRENCY_LAYER_FORM_SECTION_ID = "CURRENCY_LAYER_FORM_SECTION_ID";
	public static final String CURRENCY_LAYER_API_URL_FIELD_ID = "CURRENCY_LAYER_API_URL_FIELD_ID";
	public static final String CURRENCY_LAYER_API_ACCESS_TOKEN_FIELD_ID = "CURRENCY_LAYER_API_ACCESS_TOKEN_FIELD_ID";
	public static final String CURRENCY_LAYER_REFRESH_INTERVAL_FIELD_ID = "CURRENCY_REFRESH_INTERVAL_FIELD_ID";
	
	public static final String HOLIDAY_API_FORM_SECTION_ID = "HOLIDAY_API_FORM_SECTION_ID";
	public static final String HOLIDAY_API_URL_FIELD_ID = "HOLIDAY_API_URL";
	public static final String HOLIDAY_API_KEY_FIELD_ID = "HOLIDAY_API_KEY";
	
	public static final String IS_HOLIDAY_DATA_AVAILABLE_$COUNTRY = "IS_HOLIDAY_DATA_AVAILABLE_$COUNTRY";

	
	public static final String IS_PROPERTY_PRICE_RULES_ENABLED = "IS_PROPERTY_PRICE_RULES_ENABLED";
	
	public static final String EXPERT_LEVEL_EXPERIENCE_YEARS = "EXPERT_LEVEL_EXPERIENCE_YEARS";
	public static final String DEFAULT_AGENT_ORGANIZATION_RATING = "DEFAULT_AGENT_ORGANIZATION_RATING";
}
